name: flutter_crud_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  camera_camera: ^3.0.0
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  file_picker: ^5.5.0
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_svg: ^2.0.7
  geolocator: ^10.1.0
  get: 4.6.5
  image_cropper: ^5.0.0
  intl: ^0.18.1
  latlong2: ^0.9.0
  qr_code_dart_scan: ^0.7.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
