// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFC57HkuW3fbtxBtPEwW5waGivlquzCmE',
    appId: '1:34659403193:web:7d25c686faeedcee1d2268',
    messagingSenderId: '34659403193',
    projectId: 'todolist-app-3b778',
    authDomain: 'todolist-app-3b778.firebaseapp.com',
    storageBucket: 'todolist-app-3b778.appspot.com',
    measurementId: 'G-JL5ZKBN8VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH-222GpYu28OpYDOAqqFyAcpn2zb178o',
    appId: '1:34659403193:android:e75b0522a9d478451d2268',
    messagingSenderId: '34659403193',
    projectId: 'todolist-app-3b778',
    storageBucket: 'todolist-app-3b778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQQ0zZf7sY-NOzYSDns_WL_Qthq0vr40',
    appId: '1:34659403193:ios:bea3c44b5c4b2c271d2268',
    messagingSenderId: '34659403193',
    projectId: 'todolist-app-3b778',
    storageBucket: 'todolist-app-3b778.appspot.com',
    iosClientId: '34659403193-p5do58413t4q2keh71ldsv0t6u9qv2p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNQQ0zZf7sY-NOzYSDns_WL_Qthq0vr40',
    appId: '1:34659403193:ios:11e12767cdc6ef781d2268',
    messagingSenderId: '34659403193',
    projectId: 'todolist-app-3b778',
    storageBucket: 'todolist-app-3b778.appspot.com',
    iosClientId: '34659403193-d1fvr18hanvcsdopmqtcd6vdh5hogri9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudFirebase.RunnerTests',
  );
}
